@check/retainer
Arx-Game/arxcode pull request #309
Opened 2020-06-16 19:06 UTC by dvoraen

#### Brief overview of PR changes/additions
Adds /retainer switch to @check, allowing uses of retainer die rolls.

#### Motivation for adding to Arx
- Enables game-side checking of retainer stats, rather than using @gmcheck and "just trust me on this" for stat values.  (NOTE: They should not be able to roll crits; this may need double-checked.)
- Increases value of training retainers, because they can supplement PC skills.
- Initially supports only retainer ID rather than name; that's in the works for later.

#### Other info (issues closed, discussion etc)
Closes #292

2020-06-17 02:03 UTC, TehomCD commented
Merge conflicts, so it looks like you need to update your branch a bit. I don't recall changing rolling anytime recently, so that's kind of weird.

2020-06-17 02:09 UTC, TehomCD commented on commands/base_commands/rolling.py
> +                if skill in self.caller.db.skills:
`.db.skills` is deprecated. If you could, please use the `traitshandler` for checking skills

2020-06-17 02:12 UTC, TehomCD commented on world/roll.py
> +                    self.stats[somestat] += self.retainer.dbobj.attributes.get(somestat, 0)
accessing stats via `attributes` is also deprecated, please get via traitshandler

2020-06-17 02:12 UTC, TehomCD commented on world/roll.py
> +                skills = self.retainer.dbobj.db.skills or {}
`.db.skills` deprecated

2020-06-17 02:17 UTC, TehomCD requested changes
I think the merge conflicts are from the conversion to traitshandler and deprecation of evennia Attributes for storing skills/stats. Pretty important you update to have those changes

2020-06-17 13:49 UTC, dvoraen commented
Yeah, that was the cause.  I'll have to research why the changes didn't come down, as I was getting the Evennia updates fine (so far as I can tell).  I believe I've resolved all the merge conflicts and deprecated property calls.

2020-06-18 13:19 UTC, TehomCD approved these changes
This is great, thanks for the PR!

2020-06-18 13:20 UTC, merged